name: Bug Report
description: Bug Report
body: 
  - type: markdown
    attributes:
      value: |
        请提供以下信息
  - type: input
    attributes:
      label: Node.js Version
      description: Output of `node -v`
  - type: input
    attributes:
      label: Package(oicq) Version
      description: Installed by npm or yarn
      placeholder: latest?
  - type: dropdown
    attributes:
      label: Login Protocol
      options:
        - Android
        - aPad
        - Watch
        - iMac
        - iPad
  - type: markdown
    attributes:
      value: |
        * [x] 我已确认过官方客户端不存在此问题，库的行为存在问题。
  - type: textarea
    attributes:
      label: Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)
  - type: textarea
    attributes:
      label: Log Details (控制台日志，请提供包含前后一段时间内的)
